### ISSUE TITLE
unknown hotspot in influx and dashboard

### ISSUE THREAD

**Issue by ideasman69** [ThomDietrich/helium-exporter-grafana#3]
Hi mate,

I originally posted this to just say thanks. I _didn't_ have any issues yesteday - but couldn't find any other way to say thanks for putting this together. I was using konstk1's original one after you provided some fixes, but this version with the grafana dash is brilliant. 

...but i was just checking out the dashboard this evening and noticed that there's a third hotspot which is not in my configuration.

I've got two helium hotspot id's set using the HELIUM_HOTSPOT docker variable which has been fine since 28/04. I'm not sure where the third hotspot has come from or why its in there...

Thanks again 👍

**Comment by ThomDietrich** [comment]
I believe this was resolved. I had similar issues but changed a lot of code since then. 
Cheers!!
