### ISSUE TITLE
adding mutiple wallets

### ISSUE THREAD

**Issue by Joehoehoepi** [ThomDietrich/helium-exporter-grafana#4]
Hi there,

First of all thanks for the great work, I really enjoy using this dashboard.

I own a fleet of hotspots in different wallets. When I add mutiple wallets to the .env the update breaks with the error that the account isn't a B58 address. How do I get mutiple wallets in this .env properly?
This would give me a better overview of my earnings and height of the hnt in my wallets.

Thanks in advance!

**Comment by ThomDietrich** [comment]
Hey! Probably not relevant anymore but I don't think I will implement this. If someone wants to pull data for multiple wallets, it's probably acceptable to set up multiple docker container instances in parallel.

Please shout if you disagree. Cheers!
